/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppInvoicesRouteImport } from './routes/_app/invoices'
import { Route as AppGroupsRouteImport } from './routes/_app/groups'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAssignmentsRouteImport } from './routes/_app/assignments'
import { Route as AppSettingsUserRouteImport } from './routes/_app/settings_/user'
import { Route as AppSettingsSubjectRouteImport } from './routes/_app/settings_/subject'
import { Route as AppSettingsReportRouteImport } from './routes/_app/settings_/report'
import { Route as AppSettingsInvoiceRouteImport } from './routes/_app/settings_/invoice'
import { Route as AppSettingsGroupRouteImport } from './routes/_app/settings_/group'
import { Route as AppSettingsAssignmentRouteImport } from './routes/_app/settings_/assignment'
import { Route as AppGroupsGroupIdSessionsRouteImport } from './routes/_app/groups_/$groupId.sessions'
import { Route as AppGroupsGroupIdReportsRouteImport } from './routes/_app/groups_/$groupId.reports'
import { Route as AppGroupsGroupIdAssignmentsRouteImport } from './routes/_app/groups_/$groupId.assignments'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsRoute = AppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUserRoute = AppSettingsUserRouteImport.update({
  id: '/settings_/user',
  path: '/settings/user',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSubjectRoute = AppSettingsSubjectRouteImport.update({
  id: '/settings_/subject',
  path: '/settings/subject',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsReportRoute = AppSettingsReportRouteImport.update({
  id: '/settings_/report',
  path: '/settings/report',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsInvoiceRoute = AppSettingsInvoiceRouteImport.update({
  id: '/settings_/invoice',
  path: '/settings/invoice',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsGroupRoute = AppSettingsGroupRouteImport.update({
  id: '/settings_/group',
  path: '/settings/group',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAssignmentRoute = AppSettingsAssignmentRouteImport.update({
  id: '/settings_/assignment',
  path: '/settings/assignment',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsGroupIdSessionsRoute =
  AppGroupsGroupIdSessionsRouteImport.update({
    id: '/groups_/$groupId/sessions',
    path: '/groups/$groupId/sessions',
    getParentRoute: () => AppRoute,
  } as any)
const AppGroupsGroupIdReportsRoute = AppGroupsGroupIdReportsRouteImport.update({
  id: '/groups_/$groupId/reports',
  path: '/groups/$groupId/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsGroupIdAssignmentsRoute =
  AppGroupsGroupIdAssignmentsRouteImport.update({
    id: '/groups_/$groupId/assignments',
    path: '/groups/$groupId/assignments',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assignments': typeof AppAssignmentsRoute
  '/dashboard': typeof AppDashboardRoute
  '/groups': typeof AppGroupsRoute
  '/invoices': typeof AppInvoicesRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/settings/assignment': typeof AppSettingsAssignmentRoute
  '/settings/group': typeof AppSettingsGroupRoute
  '/settings/invoice': typeof AppSettingsInvoiceRoute
  '/settings/report': typeof AppSettingsReportRoute
  '/settings/subject': typeof AppSettingsSubjectRoute
  '/settings/user': typeof AppSettingsUserRoute
  '/groups/$groupId/assignments': typeof AppGroupsGroupIdAssignmentsRoute
  '/groups/$groupId/reports': typeof AppGroupsGroupIdReportsRoute
  '/groups/$groupId/sessions': typeof AppGroupsGroupIdSessionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assignments': typeof AppAssignmentsRoute
  '/dashboard': typeof AppDashboardRoute
  '/groups': typeof AppGroupsRoute
  '/invoices': typeof AppInvoicesRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/settings/assignment': typeof AppSettingsAssignmentRoute
  '/settings/group': typeof AppSettingsGroupRoute
  '/settings/invoice': typeof AppSettingsInvoiceRoute
  '/settings/report': typeof AppSettingsReportRoute
  '/settings/subject': typeof AppSettingsSubjectRoute
  '/settings/user': typeof AppSettingsUserRoute
  '/groups/$groupId/assignments': typeof AppGroupsGroupIdAssignmentsRoute
  '/groups/$groupId/reports': typeof AppGroupsGroupIdReportsRoute
  '/groups/$groupId/sessions': typeof AppGroupsGroupIdSessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/assignments': typeof AppAssignmentsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/groups': typeof AppGroupsRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/settings_/assignment': typeof AppSettingsAssignmentRoute
  '/_app/settings_/group': typeof AppSettingsGroupRoute
  '/_app/settings_/invoice': typeof AppSettingsInvoiceRoute
  '/_app/settings_/report': typeof AppSettingsReportRoute
  '/_app/settings_/subject': typeof AppSettingsSubjectRoute
  '/_app/settings_/user': typeof AppSettingsUserRoute
  '/_app/groups_/$groupId/assignments': typeof AppGroupsGroupIdAssignmentsRoute
  '/_app/groups_/$groupId/reports': typeof AppGroupsGroupIdReportsRoute
  '/_app/groups_/$groupId/sessions': typeof AppGroupsGroupIdSessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/assignments'
    | '/dashboard'
    | '/groups'
    | '/invoices'
    | '/profile'
    | '/settings'
    | '/users'
    | '/settings/assignment'
    | '/settings/group'
    | '/settings/invoice'
    | '/settings/report'
    | '/settings/subject'
    | '/settings/user'
    | '/groups/$groupId/assignments'
    | '/groups/$groupId/reports'
    | '/groups/$groupId/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/assignments'
    | '/dashboard'
    | '/groups'
    | '/invoices'
    | '/profile'
    | '/settings'
    | '/users'
    | '/settings/assignment'
    | '/settings/group'
    | '/settings/invoice'
    | '/settings/report'
    | '/settings/subject'
    | '/settings/user'
    | '/groups/$groupId/assignments'
    | '/groups/$groupId/reports'
    | '/groups/$groupId/sessions'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/assignments'
    | '/_app/dashboard'
    | '/_app/groups'
    | '/_app/invoices'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/users'
    | '/_app/settings_/assignment'
    | '/_app/settings_/group'
    | '/_app/settings_/invoice'
    | '/_app/settings_/report'
    | '/_app/settings_/subject'
    | '/_app/settings_/user'
    | '/_app/groups_/$groupId/assignments'
    | '/_app/groups_/$groupId/reports'
    | '/_app/groups_/$groupId/sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups': {
      id: '/_app/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assignments': {
      id: '/_app/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings_/user': {
      id: '/_app/settings_/user'
      path: '/settings/user'
      fullPath: '/settings/user'
      preLoaderRoute: typeof AppSettingsUserRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings_/subject': {
      id: '/_app/settings_/subject'
      path: '/settings/subject'
      fullPath: '/settings/subject'
      preLoaderRoute: typeof AppSettingsSubjectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings_/report': {
      id: '/_app/settings_/report'
      path: '/settings/report'
      fullPath: '/settings/report'
      preLoaderRoute: typeof AppSettingsReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings_/invoice': {
      id: '/_app/settings_/invoice'
      path: '/settings/invoice'
      fullPath: '/settings/invoice'
      preLoaderRoute: typeof AppSettingsInvoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings_/group': {
      id: '/_app/settings_/group'
      path: '/settings/group'
      fullPath: '/settings/group'
      preLoaderRoute: typeof AppSettingsGroupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings_/assignment': {
      id: '/_app/settings_/assignment'
      path: '/settings/assignment'
      fullPath: '/settings/assignment'
      preLoaderRoute: typeof AppSettingsAssignmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups_/$groupId/sessions': {
      id: '/_app/groups_/$groupId/sessions'
      path: '/groups/$groupId/sessions'
      fullPath: '/groups/$groupId/sessions'
      preLoaderRoute: typeof AppGroupsGroupIdSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups_/$groupId/reports': {
      id: '/_app/groups_/$groupId/reports'
      path: '/groups/$groupId/reports'
      fullPath: '/groups/$groupId/reports'
      preLoaderRoute: typeof AppGroupsGroupIdReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups_/$groupId/assignments': {
      id: '/_app/groups_/$groupId/assignments'
      path: '/groups/$groupId/assignments'
      fullPath: '/groups/$groupId/assignments'
      preLoaderRoute: typeof AppGroupsGroupIdAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssignmentsRoute: typeof AppAssignmentsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGroupsRoute: typeof AppGroupsRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppSettingsAssignmentRoute: typeof AppSettingsAssignmentRoute
  AppSettingsGroupRoute: typeof AppSettingsGroupRoute
  AppSettingsInvoiceRoute: typeof AppSettingsInvoiceRoute
  AppSettingsReportRoute: typeof AppSettingsReportRoute
  AppSettingsSubjectRoute: typeof AppSettingsSubjectRoute
  AppSettingsUserRoute: typeof AppSettingsUserRoute
  AppGroupsGroupIdAssignmentsRoute: typeof AppGroupsGroupIdAssignmentsRoute
  AppGroupsGroupIdReportsRoute: typeof AppGroupsGroupIdReportsRoute
  AppGroupsGroupIdSessionsRoute: typeof AppGroupsGroupIdSessionsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssignmentsRoute: AppAssignmentsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGroupsRoute: AppGroupsRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppSettingsAssignmentRoute: AppSettingsAssignmentRoute,
  AppSettingsGroupRoute: AppSettingsGroupRoute,
  AppSettingsInvoiceRoute: AppSettingsInvoiceRoute,
  AppSettingsReportRoute: AppSettingsReportRoute,
  AppSettingsSubjectRoute: AppSettingsSubjectRoute,
  AppSettingsUserRoute: AppSettingsUserRoute,
  AppGroupsGroupIdAssignmentsRoute: AppGroupsGroupIdAssignmentsRoute,
  AppGroupsGroupIdReportsRoute: AppGroupsGroupIdReportsRoute,
  AppGroupsGroupIdSessionsRoute: AppGroupsGroupIdSessionsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
